GET http://localhost:3001/api/blogs
###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhYW5pc2hyYWpAZ21haWwuY29tIiwiaWQiOjEwLCJpYXQiOjE3MDU2ODg4NDd9.iT6LpKTAOn8bQshP4jYV6TM2lSWdOfsnL9ecLijwS-Y

{
    "title": "Test me!",
    "author": "Daanish",
    "url": "www.yogananda.org",
    "likes": 1
}
###
GET http://localhost:3001/api/blogs/2
###
DELETE http://localhost:3001/api/blogs/3
###
PUT http://localhost:3001/api/blogs/4
Content-Type: application/json

{
    "title": "Deutsch is einfach!",
    "author": "Daanish",
    "url": "www.yogananda.org",
    "likes": 1952
}