GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "holyscience@yogananda-srf.org",
    "password": "sekret",
    "name": "gigi"
}
###
GET http://localhost:3001/api/users/paramhansa@yogananda-srf.org
###
PUT http://localhost:3001/api/users/daanishraj@gmail.com
Content-Type: application/json

{
    "username": "daanishraj@gmail.com",
    "password": "sekret",
    "name": "daanish"
}
###
DELETE http://localhost:3001/api/users/paramhansa@yogananda-srf.org